debug: true
server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: app-currency
          uri: http://localhost:8081/
          predicates:
            - Path=/app-converter/**
          filters:
            - AddRequestHeader=X-Request-red, blue